[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/vendor-api/*"
  to = "https://dev.alpha.study/vendor/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/courses/*"
  to = "https://dev.alpha.study/assets/courses/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
